apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      restartPolicy: Always
      containers:
      - name: backend-feed
        image: hoantat21/udagram-api-feed:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: udagram-env
          - secretRef:
              name: udagramdb-env
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret
